# Generated by Django 4.0.6 on 2022-07-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('opening_time', models.TimeField(default='00:00:00')),
                ('closing_time', models.TimeField(default='00:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
